force-app/main/default/objects/Diagram__c/Diagram__c.object-meta.xml
<CustomObject>
    <label>Diagram</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Diagrams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Diagram__c/fields/DiagramName__c.field-meta.xml
<CustomField>
    <fullName>DiagramName__c</fullName>
    <label>Diagram Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Diagram__c/fields/Documentation__c.field-meta.xml
<CustomField>
    <fullName>Documentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documentation</label>
    <referenceTo>Documentation__c</referenceTo>
    <relationshipLabel>Diagrams</relationshipLabel>
    <relationshipName>Diagrams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Diagram__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Activity</fullName>
            </value>
            <value>
                <fullName>Entity Relationship</fullName>
            </value>
            <value>
                <fullName>Flowchart</fullName>
            </value>
            <value>
                <fullName>Sequence</fullName>
            </value>
            <value>
                <fullName>Use Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Documentation__c/Documentation__c.object-meta.xml
<CustomObject>
    <label>Documentation</label>
    <nameField>
        <displayFormat>DOC-{0000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Documentation__c/fields/Documentation__c.field-meta.xml
<CustomField>
    <fullName>Documentation__c</fullName>
    <label>Documentation</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ShareDocumentationControllerTest.cls
@IsTest
public class ShareDocumentationControllerTest {
    @TestSetup
    static void makeData(){
        Documentation__c doc = new Documentation__c();
        doc.Name__c = 'Documentação teste';
        insert doc;

        Diagram__c dia = new Diagram__c();
        dia.DiagramName__c = 'Diagrama teste';
        dia.Type__c = 'Entity Relationship';
        dia.Documentation__c = doc.Id;

        insert dia;
    }

    @IsTest
    static void shareDocumentationTest(){
        Id docId = [SELECT Id FROM Documentation__c].Id;
        Id groupId = [SELECT Id FROM Group WHERE DeveloperName = 'AllInternalUsersNativeDiagrams'].Id;
        
        Test.startTest();
        Map<String,String> result = ShareDocumentationController.shareDocumentation(docId, new List<Id>{groupId}, 'Edit');
        Test.stopTest();

        System.assertEquals(result.get('status'), 'success', 'Resultado do compartilhamento deveria ser sucesso!');        
    }

    @IsTest
    static void unshareDocumentationTest(){
        Id docId = [SELECT Id FROM Documentation__c].Id;
        Id groupId = [SELECT Id FROM Group WHERE DeveloperName = 'AllInternalUsersNativeDiagrams'].Id;

        
        Test.startTest();
        ShareDocumentationController.shareDocumentation(docId, new List<Id>{groupId}, 'Edit');
        Map<String,String> result = ShareDocumentationController.unshareDocumentation(docId, groupId);
        Test.stopTest();

        System.assertEquals(result.get('status'), 'success', 'Resultado do descompartilhamento deveria ser sucesso!');        
    }

    @IsTest
    static void getRecordShareTest(){
        Id docId = [SELECT Id FROM Documentation__c].Id;
        Group groupShared = [SELECT Id, Name FROM Group WHERE DeveloperName = 'AllInternalUsersNativeDiagrams'];

        
        Test.startTest();
        ShareDocumentationController.shareDocumentation(docId, new List<Id>{groupShared.Id}, 'Edit');
        List<Map<String, String>> result = ShareDocumentationController.getRecordShare(docId);
        Test.stopTest();

        System.assertEquals(result[0].get('Name'), groupShared.Name, 'Listagem de compartilhamento vazia!');        
    }
}